networks:
  backend:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php-8.0
      - redis
    environment:
      TZ: Europe/Moscow
    networks:
      - backend

  php-8.0:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.0'
        TZ: Europe/Moscow
    working_dir: /var/www
    container_name: php-8.0
    volumes:
      - ./public:/var/www/public
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9006:9000"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./docker/redis/data:/var/lib/redis
      - ./docker/redis/conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: Europe/Moscow
    networks:
      - backend

